In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
class sistema_lineal: 
  def __init__ (self,A,b):
    self.A = A
    self.b = b
  def Jacobi(self,itmax=1000,error = 1e-10):
    M,N = self.A.shape
    x = np.zeros(N)
    sumk = np.zeros_like(x)
    x = [13,20,-1]
    it = 0
    residuo = np.linalg.norm( self.b - np.dot(self.A,x) )
    while ( residuo > error and it < itmax ):
        it += 1
        for i in range(M):
            sum_ = 0
            for j in range(N):
                if i != j:
                    sum_ += self.A[i][j]*x[j]
            sumk[i] = sum_
        for i in range(M):
            if self.A[i,i] != 0:
                x[i] = (self.b[i] - sumk[i])/self.A[i,i]
            else:
                print('No invertible con Jacobi')
        residuo = np.linalg.norm( self.b - np.dot(self.A,x) )
    return x,it,residuo
  def  Gaus_Seidel(self,itmax=1000,error = 1e-10):
    M,N = self.A.shape 
    x = np.zeros(N)
    sumk = np.zeros_like(x)
    x = [0,0,0]
    it = 0
    residuo = np.linalg.norm( self.b - np.dot(self.A,x) )
    while ( residuo > error and it < itmax ):
        it += 1
        for i in range(M):
            sum_ = 0
            for j in range(N):
                if i != j:
                    sum_ += self.A[i][j]*x[j]
            sumk[i] = sum_   
            if self.A[i,i] != 0:
                x[i] = (self.b[i] - sumk[i])/self.A[i,i]
            else:
                print('No invertible con Jacobi')
        print(x)
        residuo = np.linalg.norm( self.b - np.dot(self.A,x) )
    return x,it,residuo



In [ ]:
def Gauss_Seidel_func(A,b,itmax=1000,error = 1e-10):  
    M,N = A.shape 
    x = np.zeros(N)
    sumk = np.zeros_like(x)
    x = [0,0,0]
    it = 0
    residuo = np.linalg.norm( b - np.dot(A,x) )
    while ( residuo > error and it < itmax ):
        it += 1
        for i in range(M):
            sum_ = 0
            for j in range(N):
                if i != j:
                    sum_ += A[i][j]*x[j]
            sumk[i] = sum_   
            if A[i,i] != 0:
                x[i] = (b[i] - sumk[i])/A[i,i]
            else:
                print('No invertible con Jacobi')
        print(x)
        residuo = np.linalg.norm( b - np.dot(A,x) )
    return x,it,residuo


In [ ]:
M = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
b = np.array([1.,3.,7.])

In [ ]:
int1 = sistema_lineal(M,b)

In [ ]:
int1.Jacobi()

([1.0000000000012628, 1.0000000000109328, 0.9999999999902489],
 26,
 3.367400148824269e-11)

In [ ]:
int1.Gaus_Seidel()

[0.3333333333333333, 1.1111111111111112, 1.3055555555555556]
[1.138888888888889, 0.9444444444444445, 0.9444444444444443]
[0.9629629629629629, 1.0061728395061729, 1.0169753086419753]
[1.007716049382716, 0.9969135802469135, 0.9969135802469137]
[0.9979423868312757, 1.0003429355281206, 1.000943072702332]
[1.000428669410151, 0.9998285322359397, 0.9998285322359396]
[0.9998856881572932, 1.0000190519737846, 1.0000523929279073]
[1.0000238149672305, 0.9999904740131077, 0.9999904740131078]
[0.9999936493420719, 1.0000010584429881, 1.0000029107182171]
[1.000001323053735, 0.9999994707785059, 0.999999470778506]
[0.9999996471856707, 1.000000058802388, 1.0000001617065677]
[1.0000000735029853, 0.999999970598806, 0.9999999705988059]
[0.9999999803992039, 1.0000000032667993, 1.0000000089836982]
[1.000000004083499, 0.9999999983666003, 0.9999999983666004]
[0.999999998911067, 1.0000000001814888, 1.0000000004990943]
[1.000000000226861, 0.9999999999092556, 0.9999999999092556]
[0.9999999999395038, 1.000000000010

([1.0000000000126035, 0.9999999999949587, 0.9999999999949586],
 18,
 5.8030712832710874e-11)

In [ ]:
Gauss_Seidel_func(M,b)

[0.3333333333333333, 1.1111111111111112, 1.3055555555555556]
[1.138888888888889, 0.9444444444444445, 0.9444444444444443]
[0.9629629629629629, 1.0061728395061729, 1.0169753086419753]
[1.007716049382716, 0.9969135802469135, 0.9969135802469137]
[0.9979423868312757, 1.0003429355281206, 1.000943072702332]
[1.000428669410151, 0.9998285322359397, 0.9998285322359396]
[0.9998856881572932, 1.0000190519737846, 1.0000523929279073]
[1.0000238149672305, 0.9999904740131077, 0.9999904740131078]
[0.9999936493420719, 1.0000010584429881, 1.0000029107182171]
[1.000001323053735, 0.9999994707785059, 0.999999470778506]
[0.9999996471856707, 1.000000058802388, 1.0000001617065677]
[1.0000000735029853, 0.999999970598806, 0.9999999705988059]
[0.9999999803992039, 1.0000000032667993, 1.0000000089836982]
[1.000000004083499, 0.9999999983666003, 0.9999999983666004]
[0.999999998911067, 1.0000000001814888, 1.0000000004990943]
[1.000000000226861, 0.9999999999092556, 0.9999999999092556]
[0.9999999999395038, 1.000000000010

([1.0000000000126035, 0.9999999999949587, 0.9999999999949586],
 18,
 5.8030712832710874e-11)

In [ ]:
A = ([[1,0,0],[5,1,0],[-2,3,1]])
B = ([[4,-2,1],[0,3,7],[0,0,2]])
def Matrix_Multiplication(A,B):
  Matrix = np.zeros_like(A)
  for i in range(len(A)):
      for j in range(len(B[0])):
          for k in range(len(B)):
              Matrix[i][j] += A[i][k] * B[k][j]
  return Matrix

print(Matrix_Multiplication(A,B))
print(np.dot(A,B))

[[ 4 -2  1]
 [20 -7 12]
 [-8 13 21]]
[[ 4 -2  1]
 [20 -7 12]
 [-8 13 21]]
